### ISSUE TITLE
Linear versus persistent facts

### ISSUE THREAD

**Issue by mimoo** [tamarin-prover/manual#28]
[chapter 5](https://tamarin-prover.github.io/manual/book/005_protocol-specification.html) writes about persistent facts:

> Modeling this using linear facts would require that every rule that has such a fact in the left-hand-side, also has an exact copy of this fact in the right-hand side. While there is no fundamental problem with this modeling, it is inconvenient for the user and it also might lead Tamarin to explore rule instantiations that are irrelevant for tracing such facts.

Is this really true? From my experience it looks like I get in infinite loops doing this, while persistent facts do not get me in this awful scenario.

From discussion with @katrielalex it seems like the bang also has the property that when Tamarin looks for the source of a persistent fact, it will only pull up the rule where the instantiation of this persistent fact happened.

**Comment by katrielalex** [comment]
Specifically, I can't think of a scenario in which a rule like

```
rule Foo:
[Fact(x)]
-->
[Fact(x)]
```

will ever terminate, without a sources lemma or some other help. But perhaps I'm missing something?

**Comment by rsasse** [comment]
@katrielalex: see https://github.com/tamarin-prover/tamarin-prover/blob/develop/examples/loops/Minimal_Loop_Example.spthy for an example where exactly such a rule will terminate, thanks to the use of induction, without sources lemma. That there is a much bigger example, but related to the small one presented by me in the afternoon of the Tutorial:

theory loop
begin

rule starting:
  [ Fr(x) ]
--[ Start(x) ]->
  [ A(x) ]

rule looping:
  [ A(x) ]
--[ Loop(x) ]->
  [ A(x) ]

lemma initialize:
  "All x #i. Loop(x)@i ==> Ex #j. Start(x)@j"

end

Note that the proof will not terminate as you predict, unless one chooses "induction" or simply annotates the lemma with [use_induction].

Regarding the original question by @mimoo the statement given in the manual is technically true but probably misleading. That is, the wording "lead Tamarin to explore rule instantiations that are irrelevant" includes non-termination. Thus, for all practical purposes using persistent facts is preferred, and we should explain this better in the manual. Thanks for bringing it up!


Regarding your discussion, I am not sure I understand the point exactly, but here is some description of what happens: 
- if there is a persistent fact in some rule's premise, then Tamarin will consider all rules that produce this persistent fact in their conclusion as the source. Usually, there are few such rules (most often just 1). 
- For linear facts that are used in many rules (and kept static), obviously there are many rules with the fact in their conclusion (all of these!), and thus when looking for a source in any premise, all such rules need to be considered, which is clearly less efficient and non-termination-prone.

**Comment by mimoo** [comment]
Thanks for the precisions Ralf!

**Comment by jdreier** [comment]
Maybe we should include the essence of discussion in the manual?

**Comment by rsasse** [comment]
Yes, yes, we should. I think the discussion surrounding induction is not necessary (anyone think otherwise?), but the practical difference of linear vs persistent really should be described.

**Comment by rsasse** [comment]
I added the gist of the above discussion regarding persistent vs linear facts to the manual, in commit https://github.com/tamarin-prover/manual/commit/b309b003136045cbf0c284b6b20b9ebe5a1eb870
just now.

I hope that solves the problem. I will keep this issue open for a few more days in case anyone wants to comment.

**Comment by rsasse** [comment]
Extended in commit https://github.com/tamarin-prover/manual/commit/ff80b226176449eb7df6a277417a7dfa768be2ae

**Comment by jdreier** [comment]
I made some small changes, see commit https://github.com/tamarin-prover/manual/commit/719914e7caddcbeb457ceded8298e18390f89ab4

**Comment by rsasse** [comment]
Looks good to me. I think we can close this issue now that the manual includes these improvements.
