### ISSUE TITLE
Installation instructions outdated for Sublime Text 3

### ISSUE THREAD

**Issue by rsasse** [tamarin-prover/manual#56]
The sublime text 3 plugin was moved from a private repository to the tamarin-prover repository under https://github.com/tamarin-prover/editor-sublime

The manual https://tamarin-prover.github.io/manual/book/002_installation.html still points to the old non-existing repository and needs to be updated.

**Comment by lordqwerty** [comment]
See https://github.com/tamarin-prover/manual/pull/57

**Comment by rsasse** [comment]
Closed after accepting PR #57
