### ISSUE TITLE
Automatic update of the webpage fails

### ISSUE THREAD

**Issue by jdreier** [tamarin-prover/manual#69]
Normally Travis recompiles the HTML and PDF versions of the manual and updates the homepage on every push or merge.

Currently this does not work any more. I fixed the Travis integration and pandoc problems (by replacing outdated versions of pandoc and Ubuntu), however the push to the gh-pages still fails (see https://travis-ci.com/github/tamarin-prover/manual/builds/183856234). Can anybody knowledgeable help out? @katrielalex ?

**Comment by katrielalex** [comment]
Hmm, my guess is that the deploy key either expired or got revoked.

Unfortunately I don't have time this week to look into this (@kmilner or @mpdehnel maybe?). If I remember correctly, the architecture is that there's a file checked in called deploy_key.enc, which deploy.sh decrypts with openssl using a key and iv that are configured in the travis UI. That gives a key that should have push permissions to the github repo.

One fix might be to generate a new deploy key, figure out the openssl incantation to encrypt it, and then replace the one that's currently checked in with that. (It might make sense to replace openssl with `age` as well, although not sure if that's installable on travis.)

**Comment by jdreier** [comment]
OK I'll try installing a new key.

**Comment by jdreier** [comment]
It worked! Thanks @katrielalex 

Closing the issue.

**Comment by jdreier** [comment]
One question: There is a Netlify deploy key, is this one still used?

**Comment by katrielalex** [comment]
It seems to still be running (I think it does manual previews for pull-requests?) but I'm not sure anyone's using it.
