### ISSUE TITLE
Reference links broken in the manual

### ISSUE THREAD

**Issue by xaDxelA** [tamarin-prover/manual#72]
In the update where 
`005_protocol-specification.md `
got split into 
`005_protocol-specification-rules.md`
and
`006_protocol-specification-processes.md`
the references to each of the files seem to be not properly updated.

As an example, on the organisation section of `https://tamarin-prover.github.io/manual/book/001_introduction.html`
chapter 7 is still linked as `https://tamarin-prover.github.io/manual/book/006_property-specification.html#sec:property_specification`. 
However, the new link should be
`https://tamarin-prover.github.io/manual/book/007_property-specification.html#sec:property_specification`.

**Comment by jdreier** [comment]
Should be fixed now.
