### ISSUE TITLE
Port filter.py to Python3

### ISSUE THREAD

**Issue by rkunnema** [tamarin-prover/manual#98]
After a decade long transition, python2 is phased out and not included, e.g. in mac os anymore. We should port this little script to not make producing the manual unnecessarily difficult. Unfortunately, I don't speak in split tongues.

**Comment by darrenldl** [comment]
Filed a PR: https://github.com/rkunnema/manual/pull/2

(Only read this issue after filing said PR - let me know if you'd like me to file the PR to here directly instead.)
